### PR TITLE
add zIndex property to the spinner

### PR DESCRIPTION
**Pull request by kliput**
I added the zIndex property with this PR.

### CODE REVIEW

**Comment by RSSchermer** [comment]
Thanks, looks good! Merging...

**Comment by kliput** [comment]
@RSSchermer do you plan to make a release to make it available on npm? (version bump)

**Comment by RSSchermer** [comment]
It should already be as 0.3.2?

**Comment by kliput** [comment]
Oh, excuse me - I didn't see the "version bump" commit so I didn't notice that your last commit included version update. Thanks :)

**Pull request merged**
