### PR TITLE
Replace bower package with NPM package

### LINKED ISSUE #6: Migrate Bower dependency to NPM?
Hey there 😄 - Seems that the plugin needs to be migrated away from Bower to NPM.

Are there any plans for this?

Cheers!

### PR DESCRIPTION
**Pull request by josh-taylor**
Closes #6

### CODE REVIEW

**Comment by RSSchermer** [comment]
Hi @josh-taylor, thanks a bunch!

Does that work without modifications to `index.js`? I suspect that if you delete your bower directory this will give errors.

**Comment by josh-taylor** [comment]
Ah, do you mean [this part of the code](https://github.com/RSSchermer/ember-spin-spinner/blob/master/index.js#L22)?

You are correct in your suspicions; it blows up! 

Sorry, didn't realise this was part of it. I'll have a look and see what I can do. I guess if I can swap it with a path to the node_modules directory it would work ok?

**Comment by RSSchermer** [comment]
> Ah, do you mean [this part of the code](https://github.com/RSSchermer/ember-spin-spinner/blob/master/index.js#L22)?

Yes, exactly. 

> I guess if I can swap it with a path to the node_modules directory it would work ok?

Looking at the spin.js npm package, I actually doubt that'd do it.

I have some time this afternoon. I'll do some digging.

**Comment by RSSchermer** [comment]
Alright, I think I have something that works, I'll release it as 0.4.0 in a minute

**Comment by RSSchermer** [comment]
Should be published. Let me know if everything is working correctly for you with 0.4.0.

**Comment by josh-taylor** [comment]
Cool, thanks for this. I'm actually running on quite an old version of Ember (1.13) so it's not working for me right now.

So I'm going through the steps to update and will try it out when I'm on the 3.x version when I think the addon has access to `_findHost()`.

I guess we can close this now though?

**Comment by RSSchermer** [comment]
I'll close it for now. Feel free to reopen or open a new issue if you do run into problems later.

**Comment by josh-taylor** [comment]
All working! Thanks

**Pull request closed without merging**
